// <auto-generated />
using System;
using LyricsScraping.DAL.DatabaseEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LyricsScraping.Migrations
{
    [DbContext(typeof(LyricsDbContext))]
    partial class LyricsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("LyricsScraping.DAL.DatabaseEntities.Lyrics", b =>
                {
                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreationTime");

                    b.Property<DateTime>("DownloadTime");

                    b.Property<string>("Singer");

                    b.Property<string>("SingerName");

                    b.HasKey("Title")
                        .HasName("PrimaryKey_Lyrics_Title");

                    b.HasIndex("SingerName");

                    b.ToTable("Lyrics");
                });

            modelBuilder.Entity("LyricsScraping.DAL.DatabaseEntities.Singer", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name")
                        .HasName("PrimaryKey_Singer_Name");

                    b.ToTable("Singer");
                });

            modelBuilder.Entity("LyricsScraping.DAL.DatabaseEntities.Lyrics", b =>
                {
                    b.HasOne("LyricsScraping.DAL.DatabaseEntities.Singer")
                        .WithMany("Lyrics")
                        .HasForeignKey("SingerName");
                });
#pragma warning restore 612, 618
        }
    }
}
